[platformio]
default_envs = watchy_v2
src_dir = main

[env:watchy_v2]
platform = espressif32
board = pico32
framework = espidf
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
