#ifndef WATCHY_BOARD_H
#define WATCHY_BOARD_H

#define WATCHY_PIN_I2C_SDA 21
#define WATCHY_PIN_I2C_SCL 22

#define WATCHY_PIN_SPI_SCK 18
#define WATCHY_PIN_SPI_MOSI 23

#define WATCHY_PIN_DISPLAY_CS 5
#define WATCHY_PIN_DISPLAY_DC 10
#define WATCHY_PIN_DISPLAY_RESET 9
#define WATCHY_PIN_DISPLAY_BUSY 19

#define WATCHY_PIN_BUTTON_MENU 26
#define WATCHY_PIN_BUTTON_BACK 25
#define WATCHY_PIN_BUTTON_DOWN 4
#define WATCHY_PIN_BUTTON_UP 35
#define WATCHY_BUTTON_ACTIVE_LEVEL 1

#define WATCHY_PIN_MOTOR 13
#define WATCHY_PIN_BATTERY_ADC 34
#define WATCHY_PIN_RTC_INTERRUPT 27
#define WATCHY_RTC_INTERRUPT_ACTIVE_LEVEL 0
#define WATCHY_PIN_BMA423_INTERRUPT_1 14
#define WATCHY_PIN_BMA423_INTERRUPT_2 12

#endif
