#!/usr/bin/env python3
"""Generate reproducible, one-bit Watchy font strikes from vendored OTFs."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import sys
from typing import Iterable

from PIL import Image, ImageDraw, ImageFont


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CONFIG_RELATIVE_PATH = Path("tools/font_strikes.json")
GENERATOR_RELATIVE_PATH = Path("tools/generate_fonts.py")
HEADER_RELATIVE_PATH = Path("sdk/ui/generated/watchy_fonts.h")
SOURCE_RELATIVE_PATH = Path("sdk/ui/generated/watchy_fonts.c")
IBM_FONT_DIRECTORY = Path("assets/fonts/ibm-plex-mono")
HEROS_FONT_DIRECTORY = Path("assets/fonts/tex-gyre-heros")


@dataclass(frozen=True)
class Glyph:
    codepoint: int
    bitmap_offset: int
    bearing_x: int
    bearing_y: int
    width: int
    height: int
    advance: int
    stride: int


@dataclass(frozen=True)
class RenderedOutputs:
    header: bytes
    source: bytes


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_config(root: Path) -> dict:
    return json.loads((root / CONFIG_RELATIVE_PATH).read_text(encoding="utf-8"))


def source_path(root: Path, filename: str) -> Path:
    if filename.startswith("IBMPlexMono-"):
        return root / IBM_FONT_DIRECTORY / filename
    if filename.startswith("texgyreheros-"):
        return root / HEROS_FONT_DIRECTORY / filename
    raise ValueError(f"font is not a vendored source: {filename}")


def source_hashes(root: Path) -> dict[str, str]:
    config = load_config(root)
    names = sorted({strike["font"] for strike in config["strikes"]})
    return {name: sha256(source_path(root, name)) for name in names}


def strike_codepoints(config: dict, strike_id: str) -> list[int]:
    strike = next(strike for strike in config["strikes"] if strike["id"] == strike_id)
    return sorted({ord(character) for character in strike.get("glyphs", config["glyphs"])})


def pack_rows_msb_first(mask: Image.Image, threshold: int) -> tuple[bytes, int]:
    width, height = mask.size
    stride = (width + 7) // 8
    packed = bytearray(stride * height)
    pixels = mask.load()
    for y in range(height):
        for x in range(width):
            if pixels[x, y] >= threshold:
                packed[y * stride + x // 8] |= 0x80 >> (x % 8)
    return bytes(packed), stride


def rasterize(font: ImageFont.FreeTypeFont, codepoint: int, threshold: int) -> tuple[Glyph, bytes]:
    character = chr(codepoint)
    left, top, right, bottom = font.getbbox(character, anchor="ls")
    width, height = max(0, right - left), max(0, bottom - top)
    advance = round(font.getlength(character))
    if not width or not height:
        return Glyph(codepoint, 0, left, -top, 0, 0, advance, 0), b""
    mask = Image.new("L", (width, height), 0)
    ImageDraw.Draw(mask).text((-left, -top), character, fill=255, font=font, anchor="ls")
    bitmap, stride = pack_rows_msb_first(mask, threshold)
    return Glyph(codepoint, 0, left, -top, width, height, advance, stride), bitmap


def c_bytes(data: bytes) -> Iterable[str]:
    for offset in range(0, len(data), 12):
        yield ", ".join(f"0x{value:02x}" for value in data[offset:offset + 12])


def provenance_lines(root: Path) -> list[str]:
    config_hash = sha256(root / CONFIG_RELATIVE_PATH)
    generator_hash = sha256(root / GENERATOR_RELATIVE_PATH)
    return [
        f" * generator sha256: {generator_hash}",
        f" * config sha256: {config_hash}",
        *(f" * {name} sha256: {digest}" for name, digest in source_hashes(root).items()),
    ]


def render_header(root: Path, strike_ids: list[str]) -> str:
    exports = "\n".join(f"extern const watchy_font_t watchy_font_{strike_id};" for strike_id in strike_ids)
    banner = "\n".join(("/* Generated by tools/generate_fonts.py; do not edit.", *provenance_lines(root), " */"))
    return f"""{banner}
#ifndef WATCHY_FONTS_H
#define WATCHY_FONTS_H

#include <stddef.h>
#include <stdint.h>

typedef struct {{
    uint32_t codepoint;
    uint32_t bitmap_offset;
    int16_t bearing_x;
    int16_t bearing_y;
    uint16_t width;
    uint16_t height;
    uint16_t advance;
    uint16_t stride;
}} watchy_font_glyph_t;

typedef struct {{
    const watchy_font_glyph_t *glyphs;
    const uint8_t *bitmap;
    uint16_t glyph_count;
    uint8_t px;
    int8_t ascent;
    int8_t descent;
    uint8_t line_height;
}} watchy_font_t;

{exports}

const watchy_font_glyph_t *watchy_font_find_glyph(const watchy_font_t *font, uint32_t codepoint);

#endif
"""


def render_source(root: Path, config: dict) -> str:
    lines = [
        "/* Generated by tools/generate_fonts.py; do not edit.",
        *provenance_lines(root),
        " */",
        "#include \"watchy_fonts.h\"",
        "",
    ]
    for strike in sorted(config["strikes"], key=lambda item: item["id"]):
        strike_id = strike["id"]
        font = ImageFont.truetype(source_path(root, strike["font"]), strike["px"], layout_engine=ImageFont.Layout.BASIC)
        glyphs: list[Glyph] = []
        bitmap = bytearray()
        for codepoint in sorted({ord(character) for character in strike.get("glyphs", config["glyphs"])}):
            glyph, packed = rasterize(font, codepoint, strike["threshold"])
            glyphs.append(Glyph(codepoint, len(bitmap), glyph.bearing_x, glyph.bearing_y,
                                glyph.width, glyph.height, glyph.advance, glyph.stride))
            bitmap.extend(packed)
        lines.append(f"static const uint8_t bitmap_{strike_id}[] = {{")
        lines.extend(f"    {row}," for row in c_bytes(bitmap))
        lines.append("};")
        lines.append(f"static const watchy_font_glyph_t glyphs_{strike_id}[] = {{")
        lines.extend(
            "    {%d, %d, %d, %d, %d, %d, %d, %d}," % (
                glyph.codepoint, glyph.bitmap_offset, glyph.bearing_x, glyph.bearing_y,
                glyph.width, glyph.height, glyph.advance, glyph.stride,
            ) for glyph in glyphs
        )
        lines.append("};")
        ascent, descent = font.getmetrics()
        lines.append(
            f"const watchy_font_t watchy_font_{strike_id} = {{glyphs_{strike_id}, bitmap_{strike_id}, "
            f"{len(glyphs)}, {strike['px']}, {ascent}, {-descent}, {ascent + descent}}};"
        )
        lines.append("")
    lines.extend((
        "const watchy_font_glyph_t *watchy_font_find_glyph(const watchy_font_t *font, uint32_t codepoint) {",
        "    size_t low = 0;",
        "    size_t high = font->glyph_count;",
        "    while (low < high) {",
        "        const size_t middle = low + (high - low) / 2;",
        "        const uint32_t candidate = font->glyphs[middle].codepoint;",
        "        if (candidate == codepoint) return &font->glyphs[middle];",
        "        if (candidate < codepoint) low = middle + 1; else high = middle;",
        "    }",
        "    return NULL;",
        "}",
        "",
    ))
    return "\n".join(lines)


def render_outputs(root: Path) -> RenderedOutputs:
    config = load_config(root)
    strike_ids = [strike["id"] for strike in sorted(config["strikes"], key=lambda item: item["id"])]
    return RenderedOutputs(render_header(root, strike_ids).encode("ascii"), render_source(root, config).encode("ascii"))


def generated_paths(root: Path) -> tuple[Path, Path]:
    return root / HEADER_RELATIVE_PATH, root / SOURCE_RELATIVE_PATH


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if checked-in artifacts differ")
    arguments = parser.parse_args()
    outputs = render_outputs(REPOSITORY_ROOT)
    header_path, source_path = generated_paths(REPOSITORY_ROOT)
    if arguments.check:
        if header_path.read_bytes() == outputs.header and source_path.read_bytes() == outputs.source:
            print("font strikes are up to date")
            return 0
        print("font strikes differ; run tools/generate_fonts.py", file=sys.stderr)
        return 1
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_bytes(outputs.header)
    source_path.write_bytes(outputs.source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
